version: '3.8'

services:
  go-api:
    build: .
    container_name: go-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - AIR_WD=/app

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - go-api

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis

volumes:
  postgres_data:
