name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o my-go-api ./api/main.go

      - name: Test the application
        run: go test ./...

      - name: Prepare for deployment
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.general

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/your_user/my-go-api/
            ansible-playbook -i ansible/hosts ansible/playbook.yml
